sudo: required

language:
install: true

jdk: openjdk8

env:
  global:
    - USER=OSOSystem
    - EMAIL=contact@ososystem.de
    - FILES="build/asciidoc/html5/index.html"
    - REPO="oso-api-docs"
    - GH_REPO="github.com/${USER}/${REPO}.git"

addons:
  sonarcloud:
    organization: "ososystem" 
    token:
      secure: $SONAR_TOKEN 
    
before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
  - ./gradlew check --stacktrace
  - ./gradlew bootJar
  - ./gradlew asciidoctor
  - fossa init
  - fossa analyze
  - sonar-scanner

services:
  - docker

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t ososystem/backend .
  - docker push ososystem/backend
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git clone git://${GH_REPO}
  - mv -f ${FILES} ${REPO}
  - cd ${REPO}
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git add ${FILES}
  - git commit -m ${MESSAGE}
  - git push "https://${GITHUB_TOKEN}@${GH_REPO}" master > /dev/null 2>&1

after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL