sudo: required

language:
install: true

jdk: openjdk8

env:
  global:
    - USER="oso-system"
    - EMAIL="contact@ososystem.de"
    - DOC_PATH="build/asciidoc/html5"
    - FILE="index.html"
    - REPO="oso-api-docs"
    - GH_REPO="github.com/OSOSystem/${REPO}.git"

addons:
  sonarcloud:
    organization: "ososystem" 
    token:
      secure: $SONAR_TOKEN 
    
before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
  - ./gradlew check --stacktrace
  - ./gradlew bootJar
  - ./gradlew asciidoctor
  - fossa init
  - fossa analyze
  - sonar-scanner

services:
  - docker

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t ososystem/backend .
  - docker push ososystem/backend
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - TOKEN="${GITHUB_TOKEN}"
  - chmod +x push-api-documentation.sh
  - ./push-api-documentation.sh USER EMAIL DOC_PATH FILE REPO GH_REPO MESSAGE TOKEN

after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
