version: '3.7'
services:
  postgres:
    ports:
      - "5432:5432"

  ososystem:
    ports:
      - "8000:8000"
      - "8081:8081"
      - "9999:9999"
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

  keycloak:
    environment:
      - KEYCLOAK_USER=developer
      - KEYCLOAK_PASSWORD=ososystem
      - KEYCLOAK_IMPORT=/tmp/oso-realm.json
      - PROXY_ADDRESS_FORWARDING=true
      - DB_USER=developer
      - DB_PASSWORD=ososystem
    ports:
      - "8080:8080"