spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oso?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: developer
    password: ososystem
  mail:
    host:
    port:
    username:
    password: